//Users

const users = [
     { users_id: 1, username: "syltbar", password: "syltbar" },
     { users_id: 2, username: "Yuki", password: "iAmSmol" },
     { users_id: 3, username: "Nacho", password: "iAmBig" },
];

const drinks = [
     {
          drinks_id: 1,
          cocktails_db_drinks_id: 12564,
          drink_name: "Apple Karate",
          ingredients: "Apple juice",
          recipe: "",
          image: "",
          glass: "",
          alcoholic: false,
     },
     {
          drinks_id: 2,
          cocktails_db_drinks_id: 12668,
          drink_name: "Egg cream",
          ingredients: "Milk",
          recipe: "",
          image: "",
          glass: "",
          alcoholic: false,
     },
     {
          drinks_id: 3,
          cocktails_db_drinks_id: 12748,
          drink_name: "Orange Scented Hot Chocolate",
          ingredients: "Milk",
          recipe: "",
          image: "",
          glass: "",
          alcoholic: false,
     },
     {
          drinks_id: 4,
          cocktails_db_drinks_id: 12780,
          drink_name: "Spiking coffee",
          ingredients: "Coffee",
          recipe: "",
          image: "",
          glass: "",
          alcoholic: false,
     },
     {
          drinks_id: 5,
          cocktails_db_drinks_id: 12784,
          drink_name: "Thai Iced Coffee",
          ingredients: "Coffee",
          recipe: "",
          image: "",
          glass: "",
          alcoholic: false,
     },
     {
          drinks_id: 6,
          cocktails_db_drinks_id: 16958,
          drink_name: "Apple Pie with A Crust",
          ingredients: "Rum",
          recipe: "",
          image: "",
          glass: "",
          alcoholic: true,
     },
     {
          drinks_id: 7,
          cocktails_db_drinks_id: 15597,
          drink_name: "Absolut Stress #2",
          ingredients: "Vodka",
          recipe: "",
          image: "",
          glass: "",
          alcoholic: true,
     },
     {
          drinks_id: 8,
          cocktails_db_drinks_id: 17226,
          drink_name: "Adam & Eve",
          ingredients: "Vodka",
          recipe: "",
          image: "",
          glass: "",
          alcoholic: true,
     },
     {
          drinks_id: 9,
          cocktails_db_drinks_id: 11050,
          drink_name: "Apricot Lady",
          ingredients: "Rum",
          recipe: "",
          image: "",
          glass: "",
          alcoholic: true,
     },
     {
          drinks_id: 10,
          cocktails_db_drinks_id: 178325,
          drink_name: "Aperol Spritz",
          ingredients: "Prosecco",
          recipe: "",
          image: "",
          glass: "",
          alcoholic: true,
     },
];
